sudo: required
services:
  - docker

before_install:
  - docker build -t stefan1982/docker-react -f Dockerfile.dev .

script:
  - travis_wait 30 docker run stefan1982/docker-react CI=true npm run test
